<?php require('header.phtml') ?>
<style>
.container{width: 100%;padding: 50px;}
.table{width: 65%;float: left;}
.shipAddr{width: 30%;float: left;margin-left: 30px;}
.footBtn{width: 95%;float: left;}
.orderBtn {float: right;}
</style>

<h1>Order Preview</h1>
<table class="table">
<thead>
    <tr>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Subtotal</th>
    </tr>
</thead>
<tbody>
    <?php
    if($cart->total_items() > 0){
        //get cart items from session
        $cartItems = $cart->contents();
        foreach($cartItems as $item){
    ?>
    <tr>
        <td><?php echo $item["name"]; ?></td>
        <td><?php echo '£'.$item["price"]; ?></td>
        <td><?php echo $item["qty"]; ?></td>
        <td><?php echo '£'.$item["subtotal"]; ?></td>
    </tr>
    <?php } }else{ ?>
    <tr><td colspan="4"><p>No items in your cart......</p></td>
    <?php } ?>
</tbody>
<tfoot>
    <tr>
        <td colspan="3"></td>
        <?php if($cart->total_items() > 0){ ?>
        <td class="text-center"><strong>Total <?php echo '£'.$cart->total(); ?></strong></td>
        <?php } ?>
    </tr>
</tfoot>
</table>
<div class="shipAddr">
  <?php
  $custRow = $_SESSION['userData'];
  ?>
    <p><?php echo $custRow['first_name']; ?></p>
    <p><?php echo $custRow['email']; ?></p>
    <p><?php echo $custRow['mobile_number']; ?></p>
    <p><?php echo $custRow['address']; ?></p>
</div>
<div class="footBtn">
    <a href="index.php" class="btn btn-warning"><i class="glyphicon glyphicon-menu-left"></i> Continue Shopping</a>
    <a href="cart.php?action=placeOrder" class="btn btn-success orderBtn">Place Order <i class="glyphicon glyphicon-menu-right"></i></a>
</div>
<?php require('footer.phtml') ?>
