</div>
  <div class="subnavbar">
    <div class="subnavbar-inner">
      <div class="container">
        <ul class="mainnav">
          <li><a href="dashboard.php"><i class="fa fa-tachometer fa-4"aria-hidden="true"></i><span>Dashboard</span></a></li>
          <li><a href="products.php"><i class="fa fa-address-card fa-4"aria-hidden="true"></i><span>Add Product</span></a></li>
          <li><a href="update.php"><i class="fa fa-pencil-square-o fa-4"aria-hidden="true"></i><span>Edit Product</span></a></li>
          <li><a href="review_list.php"><i class="fa fa-comments fa-4"aria-hidden="true"></i><span>Manage Reviews</span></a></li>
          <li><a href="user_list.php"><i class="fa fa-user-plus fa-4"aria-hidden="true"></i><span>Edit users</span></a></li>
        </ul>
      </div> <!-- /container -->
    </div> <!-- /subnavbar-inner -->
  </div> <!-- /subnavbar -->
  <div class="container">
