<?php require('header.phtml') ?>
<?php require('view/dashboardHeader.phtml') ?>
    <div class="row main">
      <div class="panel-heading">
        <div class="panel-title text-center">
          <p>Edit Product</p><hr/>
        </div>
      </div>
      <div class="col-md-4 col-md-offset-4">
        <form class="" action="/update.php" method="post" enctype="multipart/form-data">
          <div class="form-group">
            <label for="name" class="cols-sm-2 control-label">Product Name</label>
            <div class="cols-sm-10">
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
                <input type="text" class="form-control" name="name" id="name" value="<?php echo $view->productRepository['name'];?>">
              </div>
            </div>
          </div>

          <div class="form-group">
            <label for="email" class="cols-sm-2 control-label">Price</label>
            <div class="cols-sm-10">
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-gbp fa" aria-hidden="true"></i></span>
                <input type="text" class="form-control" name="price" id="price"  value="<?php echo $view->productRepository['price'];?>">
              </div>
            </div>
          </div>

          <div class="form-group">
            <label for="username" class="cols-sm-2 control-label">Description</label>
            <div class="cols-sm-10">
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-newspaper-o fa" aria-hidden="true"></i></span>
                <textarea class="form-control" name="description"rows="5" id="description"><?php echo $view->productRepository['description'];?></textarea>
              </div>
            </div>
          </div>

          <div class="form-group">
            <label for="category_id" class="cols-sm-2 control-label">Category</label>
            <div class="cols-sm-10">
              <div class="input-group">
                      <label class="radio-inline"><input type="radio" id="category_id_men" name="category_id" value="1"> Men</label>
                      <label class="radio-inline"><input type="radio" id="category_id_woman" name="category_id" value="2"> Woman</label>
                      <label class="radio-inline"><input type="radio" id="category_id_children" name="category_id" value="3"> Children</label>
                </div>
              </div>
          </div>

          <div class="form-group">
            <label for="stock_qty" class="cols-sm-2 control-label">Stock qty</label>
            <div class="cols-sm-10">
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa fa-exchange fa-lg" aria-hidden="true"></i></span>
                <input type="text" class="form-control" name="stock_qty" id="stock_qty"  value="<?php echo $view->productRepository['stock_qty'];?>">
              </div>
            </div>
          </div>

          <div class="form-group">
            <label for="image" class="cols-sm-2 control-label">Image file</label>
            <div class="cols-sm-10">
              <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-file-image-o fa-lg" aria-hidden="true"></i></span>
                <input type="file" class="form-control" name="image" id="image">
              </div>
            </div>
          </div>

          <div class="form-group ">
            <input type="hidden" name="id" value=<?php echo $view->productRepository['id'];?>>
            <input type="submit" class="btn btn-info" value="Update Product">
          </div>
        </form>
      </div>
    </div>

<?php require('footer.phtml') ?>
