    </div>

    <div class="footer">
        <div class="container">
          <div class="row">
            <div class="col-md-3 col-sm-6">
              <div class="title-footer"><span>About Us</span></div>
              <ul>
                <li>
                  Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et doloremmagna aliqua. Ut enim ad minim... <a href="#">Read More</a>
                </li>
              </ul>
            </div>
            <div class="col-md-3 col-sm-6">
              <div class="title-footer"><span>Information</span></div>
              <ul>
                <li><i class="fa fa-angle-double-right"></i> <a href="#">FAQ</a></li>
                <li><i class="fa fa-angle-double-right"></i> <a href="#">Policy Privacy</a></li>
                <li><i class="fa fa-angle-double-right"></i> <a href="#">Terms and Conditions</a></li>
                <li><i class="fa fa-angle-double-right"></i> <a href="#">Shipping Methods</a></li>
              </ul>
            </div>
            <div class="clearfix visible-sm-block"></div>
            <div class="col-md-3 col-sm-6">
              <div class="title-footer"><span>Categories</span></div>
              <ul>
                <li><i class="fa fa-angle-double-right"></i> <a href="#">Cras justo odio</a></li>
                <li><i class="fa fa-angle-double-right"></i> <a href="#">Dapibus ac facilisis in</a></li>
                <li><i class="fa fa-angle-double-right"></i> <a href="#">Morbi leo risus</a></li>
                <li><i class="fa fa-angle-double-right"></i> <a href="#">Porta ac consectetur ac</a></li>
              </ul>
            </div>
            <div class="col-md-3 col-sm-6">
              <div class="title-footer"><span>Newsletter</span></div>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum, soluta, tempora, ipsa voluptatibus porro vel laboriosam</p>
              <div class="input-group">
                <input class="form-control" type="text" placeholder="Email Address">
                <span class="input-group-btn">
                  <button class="btn btn-default subscribe-button" type="button">Subscribe</button>
                </span>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-3 col-sm-6">
              <div class="title-footer"><span>Our Store</span></div>
              <ul class="footer-icon">
                <li><span><i class="fa fa-map-marker"></i></span> 212 Lorem Ipsum. Dolor Sit, Amet</li>
                <li><span><i class="fa fa-phone"></i></span> +123-456-789</li>
                <li><span><i class="fa fa-envelope"></i></span> <a href="mailto:cs@domain.tld">cs@domain.tld</a></li>
              </ul>
            </div>
            <div class="col-md-3 col-sm-6">
              <div class="title-footer"><span>Follow Us</span></div>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum</p>
              <ul class="follow-us">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                <li><a href="#"><i class="fa fa-rss"></i></a></li>
              </ul>
            </div>
            <div class="clearfix visible-sm-block"></div>
            <div class="col-md-3 col-sm-6">
              <div class="title-footer"><span>Payment Method</span></div>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum, soluta, tempora, ipsa voluptatibus porro vel laboriosam</p>
              <img src="img/payment-1.png" alt="Payment-1">
              <img src="img/payment-2.png" alt="Payment-2">
              <img src="img/payment-3.png" alt="Payment-3">
              <img src="img/payment-4.png" alt="Payment-4">
              <img src="img/payment-5.png" alt="Payment-5">
            </div>
            <div class="col-md-3 col-sm-6">
              <div class="title-footer"><span>My Account</span></div>
              <ul>
                <li><i class="fa fa-angle-double-right"></i> <a href="#">Orders</a></li>
                <li><i class="fa fa-angle-double-right"></i> <a href="#">Vouchers</a></li>
                <li><i class="fa fa-angle-double-right"></i> <a href="#">Points</a></li>
                <li><i class="fa fa-angle-double-right"></i> <a href="#">Logout</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="text-center copyright">
          Copyright © 2016 Mimity All right reserved
        </div>
      </div>


    <script src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <!-- Bootstrap JS file -->
    <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- Custom JS file -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script type="text/javascript" src="https://cdn.rawgit.com/igorlino/elevatezoom-plus/1.1.6/src/jquery.ez-plus.js"></script>
    <script type="text/javascript" src="js/script.js"></script>




</body>
</html>
