<?php require('header.phtml') ?>
<style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 100%;
      height: 345px;
      margin: auto;
  }
  </style>
</div>
  <section>
          <div id="myCarousel" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox">
            <div class="item active">
              <img src="img/img1.jpg" alt="Chania" width="460" height="345">
            </div>

            <div class="item">
              <img src="img/img2.jpg" alt="Chania" width="460" height="345">
            </div>

            <div class="item">
              <img src="img/img3.jpg" alt="Flower" width="460" height="345">
            </div>

            <div class="item">
              <img src="img/img2.jpg" alt="Flower" width="460" height="345">
            </div>
          </div>
          <!-- Left and right controls -->
            <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
         </div>

  </section>
  <br>
  <div class="container">
  <div class="form-group col-md-12">
  <div class="col-md-2 ">
  <form name="sort" action="index.php" method="post">

    <select class="form-control" name="order" data-style="btn-primary" >
      <option value="">Sort by</option>
      <option value="price-asc">Price (Lowest)</option>
      <option value="price-desc">Price (Highest)</option>
      <option value="category">Category</option>
      <option value="name">Name</option>
    </select>
  </div>
  <div class="col-md-2">

    <select class="form-control" name="numbers">
      <option value="">Results per page</option>
      <option value="4">4</option>
      <option value="8">8</option>
      <option value="12">12</option>
    </select>
  </div>
  <div class="col-md-2">
  <input type="submit" class="btn btn-success " type="button" value="sort">
</div>
</form>
</div>


<div class="row">
  <?php foreach ($pagination as $p) {
      foreach ($p as $products) { ?>
    <!-- BEGIN PRODUCTS -->
    <div class="col-md-3 col-sm-6">
      <span class="thumbnail">
        <a href="<?php echo 'page.php?id='.$products->getProductID();?>">
          <img src="/img/<?php echo $products->getImageName();?>" class="img-responsive" alt="product">
        </a>
          <h4><?php echo $products->getProductName();?></h4>
          <div class="ratings">
                  <span class="glyphicon glyphicon-star"></span>
                  <span class="glyphicon glyphicon-star"></span>
                  <span class="glyphicon glyphicon-star"></span>
                  <span class="glyphicon glyphicon-star"></span>
                  <span class="glyphicon glyphicon-star-empty"></span>
              </div>
          <p><?php echo $products->getDescription();?></p>
          <hr class="line">
          <div class="row">
            <div class="col-md-12 col-sm-6 text-center">
              <p class="price">£<?php echo $products->getPrice();?></p>
            </div>
            <div class="col-md-12 col-sm-6 ">
                <a class="btn btn-success col-md-12" href="cart.php?action=addToCart&id=<?php echo $products->getProductID();?>">Add to cart</a>
            </div>
          </div>
      </span>
    </div>
  <?php }} ?>
</div>

<?php foreach ($numbers as $n) {
    
    echo '<ul class="pagination">';

    if($_GET['page'] == $n){
      echo '<li class="active">' ;
    } else{
      echo '<li>' ;
    }
      echo '<a href="index.php?page=' . $n . '">'. $n .'</a>'. ' ' .
          '</li>' ;
    echo '</ul>' ;

  }
?>


<?php require('footer.phtml') ?>
