<?php require('header.phtml') ?>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2>

            </h2>
        </div>
    </div>

    <div class="row">
        <div class="col-md-5 well">
            <h4>Register</h4>
            <?php
            if ($register_error_message != "") {
                echo '<div class="alert alert-danger"><strong>Error: </strong> ' . $register_error_message . '</div>';
            }
            ?>
            <form action="/register.php" method="post">
              <div class="form-group row">
                <label for="example-text-input" class="col-xs-2 col-form-label">First Name</label>
                <div class="col-xs-10">
                  <input class="form-control" type="text"  name="first_name">
                </div>
              </div>
              <div class="form-group row">
                <label for="example-search-input" class="col-xs-2 col-form-label">Last Name</label>
                <div class="col-xs-10">
                  <input class="form-control" type="last_name"  name="last_name">
                </div>
              </div>
              <div class="form-group row">
                <label for="example-email-input" class="col-xs-2 col-form-label">Email</label>
                <div class="col-xs-10">
                  <input class="form-control" type="email"  name="email">
                </div>
              </div>
              <div class="form-group row">
                <label for="example-url-input" class="col-xs-2 col-form-label">Password</label>
                <div class="col-xs-10">
                  <input class="form-control" type="password" name="password">
                </div>
              </div>
              <div class="form-group row">
                <label for="example-tel-input" class="col-xs-2 col-form-label">Mobile Number</label>
                <div class="col-xs-10">
                  <input class="form-control" type="tel"  name="mobile_number">
                </div>
              </div>
              <div class="form-group row">
                <label for="example-tel-input" class="col-xs-2 col-form-label">Address</label>
                <div class="col-xs-10">
                  <input class="form-control" type="tel"  name="address">
                </div>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-5 well">
            <h4>Login</h4>
            <?php
            if ($login_error_message != "") {
                echo '<div class="alert alert-danger"><strong>Error: </strong> ' . $login_error_message . '</div>';
            }
            ?>
            <form action="<?php echo $_SERVER['PHP_SELF'];?>" method="post">
                <div class="form-group">
                    <label for="">Username/Email</label>
                    <input type="text" name="email" class="form-control"/>
                </div>
                <div class="form-group">
                    <label for="">Password</label>
                    <input type="password" name="password" class="form-control"/>
                </div>
                <div class="form-group">
                    <input type="submit" name="submit" class="btn btn-primary" value="Login"/>
                </div>
            </form>
        </div>
    </div>
</div>
<?php require('footer.phtml') ?>
