<?php require('header.phtml') ?>
<div class="container">
		<div class="card">
			<div class="container-fliud">
				<div class="wrapper row">
					<div class="preview col-md-6">
						<div class="preview-pic tab-content">
						  <div class="tab-pane active" id="pic-1"><img src="img/<?php echo $view->productRepository['image_name'];?>" /></div>
						  <div class="tab-pane" id="pic-2"><img src="img/<?php echo $view->productRepository['image_name'];?>" /></div>
						  <div class="tab-pane" id="pic-3"><img src="img/<?php echo $view->productRepository['image_name'];?>" /></div>
						  <div class="tab-pane" id="pic-4"><img src="img/<?php echo $view->productRepository['image_name'];?>" /></div>
						  <div class="tab-pane" id="pic-5"><img src="img/<?php echo $view->productRepository['image_name'];?>" /></div>
						</div>
						<ul class="preview-thumbnail nav nav-tabs">
						  <li class="active"><a data-target="#pic-1" data-toggle="tab"><img src="img/<?php echo $view->productRepository['image_name'];?>" /></a></li>
						  <li><a data-target="#pic-2" data-toggle="tab"><img src="img/<?php echo $view->productRepository['image_name'];?>" /></a></li>
						  <li><a data-target="#pic-3" data-toggle="tab"><img src="img/<?php echo $view->productRepository['image_name'];?>" /></a></li>
						  <li><a data-target="#pic-4" data-toggle="tab"><img src="img/<?php echo $view->productRepository['image_name'];?>" /></a></li>
						  <li><a data-target="#pic-5" data-toggle="tab"><img src="img/<?php echo $view->productRepository['image_name'];?>" /></a></li>
						</ul>
						<?php /* highlight_string("<?php\n\$data =\n" . var_export($view->productRepository, true) . ";\n?>"); */ ?>
						<p>Top Customer Reviews</p>
						<ul class="preview-thumbnail nav nav-tabs">
						<?php foreach ($view->productRepository as $k=>$v) {
										if (is_array($v)) {
												implode($v);
												echo '<p>By: '. $v['first_name'] . '</p>';
												echo '<p>'. $v['review']. '</p><br><hr>';


											}

 									}

 								?>
								</ul>

						<form class="" action="/review.php" method="post">
						<div class="form-group">
							<label for="exampleTextarea">Write a customer review</label>
							<textarea class="form-control" name="review" id="review" rows="3"></textarea>
						</div>
						<div class="form-group ">
							<input type="hidden" name="product_id" value="<?php echo $view->productRepository['id'];?>"/>
							<input type="hidden" name="user_id" value="<?php echo $_SESSION['user_id'];?>"/>
	            <input type="submit" class="btn btn-info" value="Send">
	          </div>
					</form>
					</div>
					<div class="details col-md-6 well">
						<h3 class="product-title"><?php echo $view->productRepository['name'];?></h3>
						<div class="rating">
							<div class="ratings">
		                  <span class="glyphicon glyphicon-star"></span>
		                  <span class="glyphicon glyphicon-star"></span>
		                  <span class="glyphicon glyphicon-star"></span>
		                  <span class="glyphicon glyphicon-star"></span>
		                  <span class="glyphicon glyphicon-star-empty"></span>
		              </div>
							<span class="review-no"><?php echo($k==0 ? 'no' : $k+1);?> reviews</span>
						</div>
						<p class="product-description"><?php echo $view->productRepository['description'];?></p>
						<h4 class="price">current price: <span>£<?php echo $view->productRepository['price'];?></span></h4>
						<p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>
						<h5 class="sizes">sizes:
							<span class="size" data-toggle="tooltip" title="small">s</span>
							<span class="size" data-toggle="tooltip" title="medium">m</span>
							<span class="size" data-toggle="tooltip" title="large">l</span>
							<span class="size" data-toggle="tooltip" title="xtra large">xl</span>
						</h5>
						<h5 class="colors">colors:
							<span class="color orange not-available" data-toggle="tooltip" title="Not In store"></span>
							<span class="color green"></span>
							<span class="color blue"></span>
						</h5>

							<div class="form-group">
		            <div class="cols-sm-8">
										<div class="col-sm-2">
										<input class="form-control" name="quantity" type="text" onkeypress="return isNumberKey(event)" maxlength="2" value="1">
										</div>
										<a class="btn btn btn-info col-md-4" href="cart.php?action=addToCart&id=<?php echo $view->productRepository['id'];?>">Add to cart</a>
		            </div>
		          </div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
<?php require('footer.phtml') ?>
