<?php require('header.phtml') ?>
<h1>Register form</h2>
<form action="<?php echo $_SERVER['PHP_SELF'];?>" method="post">
<div class="form-group row">
  <label for="example-text-input" class="col-xs-2 col-form-label">First Name</label>
  <div class="col-xs-10">
    <input class="form-control" type="text"  name="first_name">
  </div>
</div>
<div class="form-group row">
  <label for="example-search-input" class="col-xs-2 col-form-label">Last Name</label>
  <div class="col-xs-10">
    <input class="form-control" type="last_name"  name="last_name">
  </div>
</div>
<div class="form-group row">
  <label for="example-email-input" class="col-xs-2 col-form-label">Email</label>
  <div class="col-xs-10">
    <input class="form-control" type="email"  name="email">
  </div>
</div>
<div class="form-group row">
  <label for="example-url-input" class="col-xs-2 col-form-label">Password</label>
  <div class="col-xs-10">
    <input class="form-control" type="password" name="password">
  </div>
</div>
<div class="form-group row">
  <label for="example-tel-input" class="col-xs-2 col-form-label">Mobile Number</label>
  <div class="col-xs-10">
    <input class="form-control" type="tel"  name="mobile_number">
  </div>
</div>
<div class="form-group row">
  <label for="example-tel-input" class="col-xs-2 col-form-label">Address</label>
  <div class="col-xs-10">
    <input class="form-control" type="tel"  name="address">
  </div>
</div>
<button type="submit" class="btn btn-primary">Submit</button>
<?php
            if(isset($error))
            {
               foreach($error as $error)
               {
                  ?>
                  <div class="alert alert-danger">
                      <i class="glyphicon glyphicon-warning-sign"></i> &nbsp; <?php echo $error; ?>
                  </div>
                  <?php
               }
            }
  ?>
</form>
<?php require('footer.phtml') ?>
